# Generated by Django 3.1.2 on 2020-10-30 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(max_length=64)),
                ('school', models.CharField(max_length=256)),
                ('rating', models.IntegerField()),
                ('role', models.CharField(choices=[('PU', 'Ученик'), ('TC', 'Учитель'), ('AD', 'Администратор')], max_length=2)),
                ('school_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testingSystem.class')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=262144)),
                ('output', models.CharField(max_length=262144)),
            ],
        ),
        migrations.CreateModel(
            name='Testset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tests', models.ManyToManyField(to='testingSystem.Test')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('legend', models.CharField(max_length=2048)),
                ('statement', models.CharField(max_length=16384)),
                ('samples_prefix', models.IntegerField()),
                ('time_limit', models.IntegerField()),
                ('memory_limit', models.IntegerField()),
                ('checker_path', models.CharField(max_length=128)),
                ('post_processor_path', models.CharField(max_length=128)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testingSystem.myuser')),
                ('testset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testingSystem.testset')),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('solution', models.CharField(max_length=262144)),
                ('language', models.CharField(choices=[('PY', 'Python'), ('JV', 'Java')], max_length=2)),
                ('status', models.CharField(choices=[('OK', 'Решение зачтено'), ('CE', 'Ошибка компиляции'), ('WA', 'Неверный ответ'), ('PE', 'Неверный формат вывода'), ('TL', 'Превышен лимит времени'), ('ML', 'Превышен лимит памяти'), ('RE', 'Ошибка выполнения'), ('IL', 'Превышен лимит ожидания'), ('RJ', 'Решение отклонено')], max_length=2)),
                ('failed_test_index', models.IntegerField()),
                ('memory_used', models.IntegerField()),
                ('time_used', models.IntegerField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testingSystem.myuser')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testingSystem.task')),
            ],
        ),
    ]
