# Generated by Django 3.1.2 on 2020-10-31 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='language',
            field=models.CharField(choices=[('Python', 'Python'), ('C++', 'Java')], max_length=32),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='status',
            field=models.CharField(choices=[('OK', 'Решение зачтено'), ('CE', 'Ошибка компиляции'), ('WA', 'Неверный ответ'), ('TL', 'Превышен лимит времени'), ('ML', 'Превышен лимит памяти'), ('RE', 'Ошибка выполнения'), ('IL', 'Превышен лимит ожидания'), ('RJ', 'Решение отклонено')], max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='checker_path',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='post_processor_path',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
