# Generated by Django 3.1.2 on 2020-10-31 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testingSystem', '0002_auto_20201031_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckedTest',
            fields=[
                ('test_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testingSystem.test')),
                ('status', models.CharField(choices=[('OK', 'Решение зачтено'), ('CE', 'Ошибка компиляции'), ('WA', 'Неверный ответ'), ('TL', 'Превышен лимит времени'), ('ML', 'Превышен лимит памяти'), ('RE', 'Ошибка выполнения'), ('IL', 'Превышен лимит ожидания'), ('SE', 'Ошибка сервера'), ('RJ', 'Решение отклонено')], max_length=2)),
                ('memory_used', models.IntegerField()),
                ('time_used', models.IntegerField()),
            ],
            bases=('testingSystem.test',),
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='failed_test_index',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='memory_used',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='status',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='time_used',
        ),
        migrations.AddField(
            model_name='attempt',
            name='score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attempt',
            name='checked_tests',
            field=models.ManyToManyField(to='testingSystem.CheckedTest'),
        ),
    ]
