# Generated by Django 3.1.2 on 2020-10-31 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testingSystem', '0003_auto_20201031_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='checker_path',
            new_name='checker_name',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='post_processor_path',
            new_name='post_processor_name',
        ),
    ]
