# Generated by Django 3.1.2 on 2020-10-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingSystem', '0004_auto_20201031_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkedtest',
            name='message',
            field=models.CharField(default='', max_length=262144),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='language',
            field=models.CharField(choices=[('Python', 'Python'), ('C++', 'С++')], max_length=32),
        ),
    ]
