# Generated by Django 3.1.2 on 2020-10-31 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingSystem', '0005_auto_20201031_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='language',
            field=models.CharField(choices=[('Python', 'Python'), ('C++', 'C++')], max_length=32),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
