# Generated by Django 3.1.2 on 2020-11-03 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testingSystem', '0006_auto_20201031_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkedtest',
            name='test_ptr',
        ),
        migrations.DeleteModel(
            name='Attempt',
        ),
        migrations.DeleteModel(
            name='CheckedTest',
        ),
    ]
