# Generated by Django 3.1.2 on 2020-11-03 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testingSystem', '0007_auto_20201103_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckedTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OK', 'Решение зачтено'), ('CE', 'Ошибка компиляции'), ('WA', 'Неверный ответ'), ('TL', 'Превышен лимит времени'), ('ML', 'Превышен лимит памяти'), ('RE', 'Ошибка выполнения'), ('IL', 'Превышен лимит ожидания'), ('SE', 'Ошибка сервера'), ('RJ', 'Решение отклонено'), ('TS', 'Рещение тестируется')], max_length=2)),
                ('memory_used', models.IntegerField()),
                ('time_used', models.IntegerField()),
                ('message', models.CharField(default='', max_length=262144)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testingSystem.test')),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('solution', models.CharField(max_length=262144)),
                ('language', models.CharField(choices=[('Python', 'Python'), ('C++', 'C++')], max_length=32)),
                ('score', models.FloatField(default=0)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testingSystem.myuser')),
                ('checked_tests', models.ManyToManyField(to='testingSystem.CheckedTest')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testingSystem.task')),
            ],
        ),
    ]
